service: product-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  getAll:
    handler: getAll.getProductsList
    events:
      - http:
          path: /products
          method: get
  getById:
    handler: getById.getProductById
    events:
      - http:
          path: /products/{id}
          method: get
