service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::aws-az-shop-import"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::aws-az-shop-import/*"

functions:
  upload:
    handler: handlers/importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: get
          cors: true
  parse:
    handler: handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: aws-az-shop-import
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
